services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: django
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - mynetwork



  web:
    build: .
    image: your_django_image
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/djangoShortUrl
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: django
      POSTGRES_HOST: db
    networks:
      - mynetwork



volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge
