# Generated by Django 5.1.4 on 2024-12-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlink',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
