# Generated by Django 5.1.4 on 2025-02-11 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0004_clickstats_browser_clickstats_os_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clickstats',
            name='browser',
        ),
        migrations.RemoveField(
            model_name='clickstats',
            name='os',
        ),
        migrations.AlterField(
            model_name='clickstats',
            name='clicked_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clickstats',
            name='short_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_stats', to='shorturl.shortlink'),
        ),
    ]
