# Generated by Django 5.1.4 on 2025-02-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0005_remove_clickstats_browser_remove_clickstats_os_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickstats',
            name='browser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clickstats',
            name='os',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
